[tox]
envlist =
    buildhtml
requires =
    pip >= 19.3.1

[testenv]

description = Build site

passenv = BASE_URL

deps =
    # We use these files to specify all the dependencies, and below we override
    # versions for specific testing schenarios
    -rsite_requirements.txt

allowlist_externals = bash, sed

commands =
    pip freeze

    buildhtml: bash -c "jupyter-book build --html --strict -d --check-links"

skip_install = true
